name: Test against Rails main

on:
  schedule:
    - cron: "0 0 * * *" # Run every day at 00:00 UTC
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Test ${{ matrix.gemfile }} with Ruby ${{ matrix.ruby-version }} & ${{ matrix.adapter_mysql }}
    strategy:
      fail-fast: false
      matrix:
        gemfile:
          - rails_main
        adapter_mysql:
          - mysql2
          - trilogy
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
      TEST_ADAPTER_MYSQL: ${{ matrix.adapter_mysql }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruby, Bundler and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true
      - run: bundle exec rake test

  tests_successful:
    name: Tests passing?
    needs: tests
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: |
          if ${{ needs.tests.result == 'success' }}
          then
            echo "All tests passed"
          else
            echo "Some tests failed"
            false
          fi
