name: Test against Rails main

on:
  schedule:
    - cron: "0 0 * * *" # Run every day at 00:00 UTC
  workflow_dispatch:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Test rails_main with Ruby ${{ matrix.ruby-version }}
    env:
      BUNDLE_GEMFILE: gemfiles/rails_main.gemfile
    steps:
      - uses: actions/checkout@v7
      - name: Install Ruby, Bundler and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0'
          bundler-cache: true
      - parallel:
          - name: Test with mysql2
            run: bundle exec rake test
            env: {TEST_ADAPTER_MYSQL: mysql2}
          - name: Test with trilogy
            run: bundle exec rake test
            env: {TEST_ADAPTER_MYSQL: trilogy}

  tests_successful:
    name: Tests passing?
    needs: tests
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: |
          if ${{ needs.tests.result == 'success' }}
          then
            echo "All tests passed"
          else
            echo "Some tests failed"
            false
          fi
